{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rsyslog-tls-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cert.pem: {{ .Values.tls.cert | quote }}
  key.pem: {{ .Values.tls.key | quote }}
  ca.pem: {{ .Values.tls.ca | quote }}
{{- end}}